services:
  - type: web
    name: roadguard-ai
    runtime: python
    plan: free
    buildCommand: pip install -r render-requirements.txt
    startCommand: streamlit run app/streamlit_app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: MAPPLS_STATIC_KEY
        sync: false
